version: '3.6'
services:
    apache:
        image: httpd:alpine
    nginx:
        image: nginx
    app:
        build: .
        labels:
            - traefik.frontend.rule=Host:localhost
    redis:
        image: redis:alpine
    proxy:
        image: traefik
        command: --web --docker --docker.watch --entryPoints="Name:http Address::80" --docker.domain=l.h4y.cz
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

